title: GNU Octave
email: webmaster@octave.org
description: >- # this means to ignore newlines until "baseurl:"
  GNU Octave is a programming language for scientific computing.

url: "https://octave.org"

discourse_url: "https://octave.discourse.group/"
wiki_url: "https://wiki.octave.org"
faq_url: "https://wiki.octave.org/faq"
docs_url: "https://octave.org/doc/latest/"
bugs_url: "https://bugs.octave.org/"
sourceforge_url: "https://octave.sourceforge.io"
packages_url: "https://gnu-octave.github.io/packages/"
maintainers_email: "octave-maintainers@gnu.org"
help_email: "help-octave@gnu.org"
timezone: "UTC0"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
